### ISSUE TITLE
Not working with Rails 3.2.6

### ISSUE THREAD

**Issue by camilohollanda** [neerajsingh0101/admin_data#93]
I got this error with edge github branch

NoMethodError in Admin_data/home#index

Showing /home/prakash/.bundler/ruby/1.9.1/admin_data-c90759d4e6ad/app/views/admin_data/shared/_drop_down_klasses.html.erb where line #3 raised:

undefined method `map' for nil:NilClass
Extracted source (around line #3):

1: <select class='drop_down_value_klass' id='drop_down_klasses'> 
2:   <option></option>
3:   <%= options_for_select(drop_down_for_klasses, @drop_down_url) %> 
4:   <option value="<%=admin_data_migration_information_path%>">Migration Information</option>
5: </select>
Trace of template inclusion: /home/prakash/.bundler/ruby/1.9.1/admin_data-c90759d4e6ad/app/views/admin_data/shared/_header.html.erb, /home/prakash/.bundler/ruby/1.9.1/admin_data-c90759d4e6ad/app/views/layouts/admin_data.html.erb

Changed to version 1.2.1 and restart server, it worked but gave this error when editing record:

NoMethodError in Admin_data/crud#edit

Showing /usr/local/lib/ruby/gems/1.9.1/gems/admin_data-1.2.1/app/views/admin_data/crud/misc/_form.html.erb where line #7 raised:

undefined method `primary_key_name' for #ActiveRecord::Reflection::AssociationReflection:0x9625ff8
Extracted source (around line #7):

4:     <span class='col_type'>[<%= col.type.to_s %>]</span>
5:   </div>
6:   <div class='data'>
7:     <%= form_field(klass, @model, col, f).html_safe %>
8:   </div>
9: <% end %>
10: 
Trace of template inclusion: /usr/local/lib/ruby/gems/1.9.1/gems/admin_data-1.2.1/app/views/admin_data/crud/edit.html.erb

**Comment by michaelnatkin** [comment]
I'm having this exact issue; would love any help.

**Comment by ningzhang422** [comment]
I got same error, It disappeared when i pass admin_data to my production app.
In fact, in the case, /lib/util.rb didn't call by controller/application_controller.rb. 
application_controller.rb tred to convert string to object by a function in lib/util.rb. 
another point, we should change primary_key_name to foreign_key in the file /helpers/application_helper.rb
